export const fontNames = [
  // 'baskerville-display-pt',
  // 'foco',
  // 'foco2',
  // 'foco3',
  // 'nimbus-sans',
  // 'nimbus-sans2',
  // 'nimbus-sans3',
  // 'nimbus-sans4',
  // 'omnes-pro',
  // 'omnes-pro2',
  // 'omnespro',
  'semplicitapro',
  'semplicita-pro',
];

export const fontTypes = ['woff2', 'woff', 'opentype'];

export const fontConfigs = [
  {
    file: 'semplicitapro',
    family: 'semplicitapro',
    display: 'optional',
    weight: 400,
    style: 'normal',
    stretch: 'normal',
  },
  {
    file: 'semplicitapro',
    family: 'semplicitapro',
    display: 'optional',
    weight: 700,
    style: 'normal',
    stretch: 'normal',
  },
  // {
  //   file: 'baskerville-display-pt',
  //   family: 'baskerville-display-pt',
  //   display: 'optional',
  //   weight: 400,
  //   style: 'normal',
  //   stretch: 'normal',
  // },
  // {
  //   file: 'omnes-pro',
  //   family: 'omnes-pro',
  //   display: 'optional',
  //   weight: 400,
  //   style: 'normal',
  //   stretch: 'normal',
  // },
  // {
  //   file: 'omnespro',
  //   family: 'omnes-pro',
  //   display: 'optional',
  //   weight: 300,
  //   style: 'normal',
  //   stretch: 'normal',
  // },
  // {
  //   file: 'omnes-pro2',
  //   family: 'omnes-pro',
  //   display: 'optional',
  //   weight: 500,
  //   style: 'normal',
  //   stretch: 'normal',
  // },
  // {
  //   file: 'foco',
  //   family: 'foco',
  //   display: 'optional',
  //   weight: 400,
  //   style: 'normal',
  //   stretch: 'normal',
  // },
  // {
  //   file: 'foco2',
  //   family: 'foco',
  //   display: 'optional',
  //   weight: 400,
  //   style: 'italic',
  //   stretch: 'normal',
  // },
  // {
  //   file: 'foco3',
  //   family: 'foco',
  //   display: 'optional',
  //   weight: 300,
  //   style: 'normal',
  //   stretch: 'normal',
  // },
  // {
  //   file: 'nimbus-sans',
  //   family: 'nimbus-sans',
  //   display: 'optional',
  //   weight: 400,
  //   style: 'normal',
  //   stretch: 'normal',
  // },
  // {
  //   file: 'nimbus-sans2',
  //   family: 'nimbus-sans',
  //   display: 'optional',
  //   weight: 400,
  //   style: 'italic',
  //   stretch: 'normal',
  // },
  // {
  //   file: 'nimbus-sans3',
  //   family: 'nimbus-sans',
  //   display: 'optional',
  //   weight: 700,
  //   style: 'normal',
  //   stretch: 'normal',
  // },
  // {
  //   file: 'nimbus-sans4',
  //   family: 'nimbus-sans',
  //   display: 'optional',
  //   weight: 300,
  //   style: 'normal',
  //   stretch: 'normal',
  // },
];
